name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
    steps:
    # RTCV
    - name: Checkout RTCV peer dependency
      uses: actions/checkout@v2
      with:
        repository: 'ircluzar/RTCV'
        ref: '506'
        path: 'RTCV'
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1.0.2
      with:
        nuget-version: 'latest'
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Restore Nuget packages in RTCV
      run: nuget restore '.\RTCV\'
    - name: Build RTCV
      run: msbuild '.\RTCV\RTCV.sln'

    # citra
    - name: Checkout current build target
      uses: actions/checkout@v2
      with:
        path: 'citra-vanguard'
        submodules: 'recursive'
    - name: Create Citra build directory
      working-directory: ${{runner.workspace}}\citra-vanguard\citra-vanguard
      run: New-Item -ItemType Directory -Path build
    - name: Citra prebuild
      shell: cmd
      run: |
        cd citra-vanguard\build
        cmake .. -DCITRA_DONT_BUILD_DEDICATED_ROOM=true -DCITRA_DONT_BUILD_TESTS=true -DENABLE_SDL2=false -DCITRA_USE_BUNDLED_QT=1 -DENABLE_MF=ON 2>&0 & exit 0
    - name: Citra build
      run: |
        cd citra-vanguard\build
        msbuild citra.sln
